version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: docker.giffin.org/tmcclung/docker-rails-postgres
    build:
      context: rails/.
    working_dir: /mnt/rails
    command: 
    - bundle 
    - exec 
    - rails 
    - s 
    - -p 
    - 5000 
    - -b 
    - '0.0.0.0'
    volumes:
      - ./rails:/mnt/rails
    ports:
      - "80:5000"
    links:
      - db
    depends_on:
      - db

volumes:
  postgres_data:
